apiVersion: v1
kind: Pod
metadata:
  name: workerservice
spec:
  containers:
  - name: workerservice
    image: hedfan/myworkerservice:1.0
    ports:
    - name: http
      containerPort: 80
    livenessProbe:
      httpGet:
        path: /
        port: http
