//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hedfan.Tests.Unit.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hedfan.Tests.Unit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     new Controls.RoutePicker.RoutePickerControl($jq(&apos;.routePickerContainer&apos;), [{&quot;Iata&quot;:&quot;AAR&quot;,&quot;Name&quot;:&quot;Aarhus&quot;,&quot;AbbreviatedName&quot;:&quot;Aarhus&quot;,&quot;ConnectedTo&quot;:[{&quot;Iata&quot;:&quot;TXL&quot;,&quot;Name&quot;:&quot;Berlin Tegel&quot;,&quot;TimetableUrl&quot;:&quot;/en/cheap-flights/aarhus/berlin-tegel&quot;}]},{&quot;Iata&quot;:&quot;ABZ&quot;,&quot;Name&quot;:&quot;Aberdeen&quot;,&quot;AbbreviatedName&quot;:&quot;Aberdeen&quot;,&quot;ConnectedTo&quot;:[{&quot;Iata&quot;:&quot;GVA&quot;,&quot;Name&quot;:&quot;Geneva&quot;,&quot;TimetableUrl&quot;:&quot;/en/cheap-flights/aberdeen/geneva&quot;},{&quot;Iata&quot;:&quot;LTN&quot;,&quot;Name&quot;:&quot;London Luton&quot;,&quot;TimetableUrl&quot;:&quot;/en/cheap-flights/aberdeen/london-luton&quot;}]},{&quot;Iata&quot;:&quot;AGA&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EasyJetRoutePicker {
            get {
                return ResourceManager.GetString("EasyJetRoutePicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;outboundLeg&quot;:[{&quot;monthDate&quot;:&quot;2020-04-01&quot;,&quot;shortMonthName&quot;:&quot;Apr&quot;,&quot;cheapestPrice&quot;:0.0,&quot;days&quot;:[{&quot;date&quot;:&quot;2020-04-01&quot;,&quot;dayInitial&quot;:&quot;W&quot;,&quot;flights&quot;:[null],&quot;filterPrices&quot;:[0.0,0.0,0.0]},{&quot;date&quot;:&quot;2020-04-02&quot;,&quot;dayInitial&quot;:&quot;T&quot;,&quot;flights&quot;:[null],&quot;filterPrices&quot;:[0.0,0.0,0.0]},{&quot;date&quot;:&quot;2020-04-03&quot;,&quot;dayInitial&quot;:&quot;F&quot;,&quot;flights&quot;:[null],&quot;filterPrices&quot;:[0.0,0.0,0.0]},{&quot;date&quot;:&quot;2020-04-04&quot;,&quot;dayInitial&quot;:&quot;S&quot;,&quot;flights&quot;:[null],&quot;filterPrices&quot;:[0.0,0.0,0.0]},{&quot;date&quot;:&quot;2020-04-05&quot;,&quot;dayInitial&quot;:&quot;S&quot;,&quot;flights&quot;:[null],&quot;filterPrices&quot;:[0.0,0.0, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EasyJetTimetableCallbackLtnGla {
            get {
                return ResourceManager.GetString("EasyJetTimetableCallbackLtnGla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///&lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html lang=&quot;en&quot; xml:lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;!--SC-prod-fra-sc2-green-web02--&gt;
        ///&lt;head&gt;
        ///	&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=Edge&quot; /&gt;
        ///	&lt;link rel=&quot;SHORTCUT ICON&quot; href=&quot;/favicon.ico&quot; /&gt;
        ///	&lt;title&gt;easyJet.com | Flight Timetables&lt;/title&gt;&lt;meta name=&quot;keywords&quot; content=&quot;flights, cheap flights, destination guides, travel guides, route map, inspire me, tra [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EasyJetTimetables {
            get {
                return ResourceManager.GetString("EasyJetTimetables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] OpenFlightsAirportDataSample {
            get {
                object obj = ResourceManager.GetObject("OpenFlightsAirportDataSample", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
