//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hedfan.Tests.Unit.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hedfan.Tests.Unit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     new Controls.RoutePicker.RoutePickerControl($jq(&apos;.routePickerContainer&apos;), [{&quot;Iata&quot;:&quot;AAR&quot;,&quot;Name&quot;:&quot;Aarhus&quot;,&quot;AbbreviatedName&quot;:&quot;Aarhus&quot;,&quot;ConnectedTo&quot;:[{&quot;Iata&quot;:&quot;TXL&quot;,&quot;Name&quot;:&quot;Berlin Tegel&quot;,&quot;TimetableUrl&quot;:&quot;/en/cheap-flights/aarhus/berlin-tegel&quot;}]},{&quot;Iata&quot;:&quot;ABZ&quot;,&quot;Name&quot;:&quot;Aberdeen&quot;,&quot;AbbreviatedName&quot;:&quot;Aberdeen&quot;,&quot;ConnectedTo&quot;:[{&quot;Iata&quot;:&quot;GVA&quot;,&quot;Name&quot;:&quot;Geneva&quot;,&quot;TimetableUrl&quot;:&quot;/en/cheap-flights/aberdeen/geneva&quot;},{&quot;Iata&quot;:&quot;LTN&quot;,&quot;Name&quot;:&quot;London Luton&quot;,&quot;TimetableUrl&quot;:&quot;/en/cheap-flights/aberdeen/london-luton&quot;}]},{&quot;Iata&quot;:&quot;AGA&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EasyJetRoutePicker {
            get {
                return ResourceManager.GetString("EasyJetRoutePicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;outboundLeg&quot;:[{&quot;monthDate&quot;:&quot;2020-04-01&quot;,&quot;shortMonthName&quot;:&quot;Apr&quot;,&quot;cheapestPrice&quot;:0.0,&quot;days&quot;:[{&quot;date&quot;:&quot;2020-04-01&quot;,&quot;dayInitial&quot;:&quot;W&quot;,&quot;flights&quot;:[null],&quot;filterPrices&quot;:[0.0,0.0,0.0]},{&quot;date&quot;:&quot;2020-04-02&quot;,&quot;dayInitial&quot;:&quot;T&quot;,&quot;flights&quot;:[null],&quot;filterPrices&quot;:[0.0,0.0,0.0]},{&quot;date&quot;:&quot;2020-04-03&quot;,&quot;dayInitial&quot;:&quot;F&quot;,&quot;flights&quot;:[null],&quot;filterPrices&quot;:[0.0,0.0,0.0]},{&quot;date&quot;:&quot;2020-04-04&quot;,&quot;dayInitial&quot;:&quot;S&quot;,&quot;flights&quot;:[null],&quot;filterPrices&quot;:[0.0,0.0,0.0]},{&quot;date&quot;:&quot;2020-04-05&quot;,&quot;dayInitial&quot;:&quot;S&quot;,&quot;flights&quot;:[null],&quot;filterPrices&quot;:[0.0,0.0, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EasyJetTimetableCallbackLtnGla {
            get {
                return ResourceManager.GetString("EasyJetTimetableCallbackLtnGla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 17,&quot;Patreksfjörður Airport&quot;,&quot;Patreksfjordur&quot;,&quot;Iceland&quot;,&quot;PFJ&quot;,&quot;BIPA&quot;,65.555801,-23.965,11,0,&quot;N&quot;,&quot;Atlantic/Reykjavik&quot;,&quot;airport&quot;,&quot;OurAirports&quot;
        ///492,&quot;London Luton Airport&quot;,&quot;London&quot;,&quot;United Kingdom&quot;,&quot;LTN&quot;,&quot;EGGW&quot;,51.874698638916016,-0.36833301186561584,526,0,&quot;E&quot;,&quot;Europe/London&quot;,&quot;airport&quot;,&quot;OurAirports&quot;
        ///534,&quot;Glasgow International Airport&quot;,&quot;Glasgow&quot;,&quot;United Kingdom&quot;,&quot;GLA&quot;,&quot;EGPF&quot;,55.8718986511,-4.43306016922,26,0,&quot;E&quot;,&quot;Europe/London&quot;,&quot;airport&quot;,&quot;OurAirports&quot;
        ///3376,&quot;Wuhan Tianhe International Airport&quot;,&quot;Wuhan&quot;,&quot;China&quot;,&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OpenFlightsAirportDataSample {
            get {
                return ResourceManager.GetString("OpenFlightsAirportDataSample", resourceCulture);
            }
        }
    }
}
